"""
LLM client for Vercel deployment - Fallback mode
"""

from typing import Optional
from utils.logger import logger

class LLMClient:
    """Client for content generation - Fallback mode for Vercel"""
    
    def __init__(self):
        self.timeout = 30
        self.max_tokens = 500
    
    async def call_llm(self, prompt: str, model: Optional[str] = None) -> str:
        """
        Generate content using fallback templates
        """
        logger.info("Using fallback content generator (Vercel mode)")
        return self._generate_fallback_response(prompt)
    
    def _generate_fallback_response(self, prompt: str) -> str:
        """Generate contextual fallback response"""
        
        # Extract topic
        topic = "AI and content creation"
        if "Topic:" in prompt:
            try:
                topic_line = prompt.split("Topic:")[1].split("\n")[0]
                topic = topic_line.strip()
            except:
                pass
        
        # Extract keywords
        keywords = []
        if "Key themes to include:" in prompt:
            try:
                kw_section = prompt.split("Key themes to include:")[1].split("\n")[0]
                keywords = [k.strip() for k in kw_section.split(",")[:3]]
            except:
                pass
        
        prompt_lower = prompt.lower()
        
        if "instagram" in prompt_lower:
            return f"""✨ {topic} Magic! ✨

Just discovered how AI is transforming {topic.lower()}!

{keywords[0] if keywords else 'Content'} is evolving, and we're here for it! 

What's your favorite way to create content? Drop it below! 👇

#ContentCreation #AI #Innovation #CreativeProcess"""
        
        elif "linkedin" in prompt_lower:
            return f"""I've been exploring how {keywords[0] if keywords else 'AI'} is transforming {topic.lower()}.

Key insights from my journey:
• {keywords[0] if keywords else 'AI'} tools are game-changers for content creators
• Quality content at scale is now possible with the right approach
• The future of content is collaborative between humans and AI

What's your experience with AI in content creation? Share your thoughts below! 👇

#ContentStrategy #AI #Innovation #DigitalMarketing"""
        
        else:
            return f"""# {topic}

## Introduction
The landscape of content creation is undergoing a remarkable transformation. {topic} has emerged as a powerful force in how we create, optimize, and distribute content.

## Key Benefits
1. **Increased Efficiency**: AI tools help creators produce more in less time
2. **Enhanced Quality**: Intelligent systems suggest improvements and optimizations
3. **Better Insights**: Data-driven approaches to content strategy

## Best Practices
- Start with clear goals and audience understanding
- Leverage AI for research and ideation
- Maintain human oversight for quality and authenticity
- Iterate and improve based on performance data

## Future Outlook
As technology continues to evolve, we can expect even more sophisticated tools that will further empower content creators to produce exceptional work.

---
*This content was generated by Content DNA Engine - Your AI-powered content assistant*

⏱️ Reading time: 3 minute(s)"""

# Global LLM client instance
llm_client = LLMClient()